### ISSUE TITLE
Total number of bytes quota not updated following the removal of data objects with single quote in the name

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_rule_engine_plugin_logical_quotas#113]
- [ ] main
- [ ] 4-3-stable

## Bug Report

Discovered during testing of PR #110.

Notice after the removal of the data object, `irods::logical_quotas::total_size_in_bytes` still shows 80 bytes. It should be 0 after the removal.

```
$ imeta ls -C .
AVUs defined for collection /tempZone/home/kory:
attribute: irods::logical_quotas::total_size_in_bytes
value: 0
units: 
----
attribute: irods::logical_quotas::total_number_of_data_objects
value: 0
units:
$ iput test.re "just testin'"
$ imeta ls -C .
AVUs defined for collection /tempZone/home/kory:
attribute: irods::logical_quotas::total_size_in_bytes
value: 80
units: 
----
attribute: irods::logical_quotas::total_number_of_data_objects
value: 1
units:
$ irm -f "just testin'"
$ imeta ls -C .
AVUs defined for collection /tempZone/home/kory:
attribute: irods::logical_quotas::total_size_in_bytes
value: 80
units: 
----
attribute: irods::logical_quotas::total_number_of_data_objects
value: 0
units:
```

_Originally discussed here:  https://github.com/irods/irods_rule_engine_plugin_logical_quotas/issues/94#issuecomment-2077124781_

**Comment by alanking** [comment]
I think that this may be resolved on main with the new GenQuery1 parser. While working on #125, I got the following failure:
```
FAIL [8.450s]: test_data_objects_containing_single_quotes_in_data_name_can_be_removed__issue_94 (irods.test.test_rule_engine_plugin_logical_quotas.Test_Rule_Engine_Plugin_Logical_Quotas.test_data_objects_containing_single_quotes_in_data_name_can_be_removed__issue_94)
----------------------------------------------------------------------                                                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                                                                                                File "/var/lib/irods/scripts/irods/test/test_rule_engine_plugin_logical_quotas.py", line 781, in test_data_objects_containing_single_quotes_in_data_name_can_be_removed__issue_94
    self.assert_quotas(col, expected_number_of_objects=0, expected_size_in_bytes=len(contents))                                                                                                                                                                                 
  File "/var/lib/irods/scripts/irods/test/test_rule_engine_plugin_logical_quotas.py", line 860, in assert_quotas                                                                                                                                                                    self.assertEqual(values[self.total_size_in_bytes_attribute()],          expected_size_in_bytes)
AssertionError: 0 != 66                                                                                                                                                                                                                                                         
```
So it actually updated the quota after the removal occurred.

**Comment by alanking** [comment]
Checked the box for `main` (even though I didn't change anything). Leaving open in case we want to try to address this for 4-3-stable.

**Comment by alanking** [comment]
Added resolved/invalid label since no actual changes effected the fix.
