### ISSUE TITLE
tests error out in 4-2-stable with KeyError: 'log_level'

### ISSUE THREAD

**Issue by jassigill2000** [irods/irods_rule_engine_plugin_logical_quotas#18]
for example

```
======================================================================
ERROR [2.292s]: test_violation_during_recursive_put__issue_6 (irods.test.test_rule_engine_plugin_logical_quotas.Test_Rule_Engine_Plugin_Logical_Quotas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_rule_engine_plugin_logical_quotas.py", line 499, in test_violation_during_recursive_put__issue_6
    self.enable_rule_engine_plugin(config)
  File "/var/lib/irods/scripts/irods/test/test_rule_engine_plugin_logical_quotas.py", line 545, in enable_rule_engine_plugin
    config.server_config['log_level']['rule_engine'] = 'trace'
KeyError: 'log_level'
```

**Comment by trel** [comment]
this was 4-2 only?

**Comment by korydraughn** [comment]
Yes. The tests were ported to 4-2-stable from master.

**Comment by trel** [comment]
got it - thanks
